Issue 66 add feature
unitfactoryAlumni/cheatera.pp.ua pull request #101
Opened 2019-03-27 04:16 UTC by Millon15

Considering code in RememberUserInfo::rememberCursusUsersAndSkills and RememberUserInfo::rememberProjectsUsers as junk code, need help!!!

|Issue| #66 |
| ------------ | ------------ |
| DB changed? | no |
| Test locally? | NEED HELP |
| Commit name have issue prefix? | yes |
| Update CHANGELOG.md? | AFTER HELP |

2019-03-28 20:38 UTC, setnemo requested changes

2019-03-28 20:38 UTC, omentes commented on docker-compose.yml
>      environment:
обнови файл .env-example

2019-03-28 20:38 UTC, omentes commented on helpers/RememberUserInfo.php
> +     * @var     Array
укажи аррай чего. Например, Model[]

2019-03-28 20:38 UTC, omentes commented on helpers/RememberUserInfo.php
> +    private static function isArraysIdentical($a1, $a2, $arrayKeysToCompare)
phpdoc

2019-03-28 20:38 UTC, omentes commented on helpers/RememberUserInfo.php
> +    static function dateToSqlFormat(&$date)
phpdoc

2019-03-28 20:38 UTC, omentes commented on helpers/RememberUserInfo.php
> +    private static function swapKeysInArr(&$arrToChangeKeys, $keys)
phpdoc

2019-03-28 20:38 UTC, omentes commented on helpers/RememberUserInfo.php
> +    private static function mergeChildArrByKey(&$arr, $key)
phpdoc

2019-03-28 20:38 UTC, omentes commented on helpers/RememberUserInfo.php
> +    private function makeDbAction($baseActiveRecordModel, $arrToPutIntoDb, $activeRecords)
phpdoc

2019-03-28 20:38 UTC, omentes commented on helpers/RememberUserInfo.php
> +            if ( $identicalNotFound && $index == $len  ) {
PSR-2

2019-03-28 20:38 UTC, omentes commented on helpers/RememberUserInfo.php
> +        self::swapKeysInArr($this->response, [ 'id' => 'xid' ]);
PSR-2

2019-03-28 20:38 UTC, omentes commented on helpers/RememberUserInfo.php
> +            ->Where([ 'xid' => $this->response['xid'] ])
PSR-2

2019-03-28 20:38 UTC, omentes commented on helpers/RememberUserInfo.php
> +    private function rememberCurses()
phpdoc

2019-03-28 20:38 UTC, omentes commented on helpers/RememberUserInfo.php
> +            // $project['marked'] = $project['marked'] ? 'True' : 'False';
remove all code in comment block

2019-03-28 20:38 UTC, omentes commented on helpers/ThemesHelper.php
> +// use yii\web\Cookie;
..

2019-03-28 20:38 UTC, omentes commented on helpers/ThemesHelper.php
>      private static function setCookie($value)
phpdoc

2019-03-28 20:38 UTC, omentes commented on helpers/ThemesHelper.php
> +        //     'name' => static::NAME,
....

2019-03-28 20:38 UTC, omentes commented on helpers/ThemesHelper.php
> +        // if (!$cookies->getValue(static::NAME, false)) {
...

2019-03-28 20:38 UTC, omentes commented on helpers/ThemesHelper.php
>      public static function getThemesSwitcherHtml()
phpdoc

2019-03-28 20:38 UTC, omentes commented on helpers/ThemesHelper.php
>      public static function getCurrent()
phpdoc

2019-03-28 20:38 UTC, omentes commented on helpers/ThemesHelper.php
>      public static function getDefault()
phpdoc

2019-03-28 20:38 UTC, omentes commented on my_info.php
> +$a = array (
заведи привычку не использовать деприкейтед функции даже для теста. $a = [ ... ];

2019-03-28 20:38 UTC, omentes commented
старайся всегда держать ветку без конфликтов

2019-03-30 02:25 UTC, Millon15 commented
Доки в последствии добавлю, про PSR-2, от него даже на тютюлечку отступать нельзя? Там же читаемый и понятный код вышел?!

2019-03-30 09:15 UTC, setnemo submitted a review, later dismissed
Проверил локально - у меня в профиле не почистились проекты. Так же не работает докер файл, нет енвайрмента такого, и нет примера, какой он должен быть в файле экземпл.

2019-03-30 15:50 UTC, Millon15 commented
Буду в течении полутора часов, постараюсь исправить, по енвайроменту отдельный вопрос будет. И можешь пожалуйста ответить на предыдущий вопрос: https://github.com/cheatera-pp-ua/cheatera.pp.ua/pull/101#issuecomment-478197910

2019-03-31 04:35 UTC, Millon15 commented
@omentes Отдебажил, PSR-2 теперь соблюдается практически безупречно. Добавление доков добавил отдельным ишью(#113), потом сделаю.

2019-04-04 19:37 UTC, setnemo requested changes
Не работает чистка от проектов, которые удалены в апи (после отписки от проекта)
Затирается последний логин и хост последнего логина. Эту инфу надо брать с таблицы локейшинов.
Не пересчитываются ачивки в таблице xlogins

2019-04-04 19:52 UTC, omentes commented
@Millon15 распиши, пожалуйста, какие поля в таблицах обновляются, а какие нет.
Таблица 1
поле1 - обновляется
поле2 - нет

Таблица 2
поле1 - обновляется
поле2 - нет

2019-04-06 08:20 UTC, Millon15 commented
@omentes Расписываю за изменения, которые происходят в БД при логине пользователя:

Начнём с того, что каждый раз обновляются те поля в каждой конкретной таблице(их полный список смотри ниже), в которых присутствуют изменения, т. е. если данные в БД и данные, пришедшие от апишки, разнятся, то происходить апдейт запрос в БД.

Если же от апишки пришла инфа, которой нет в БД, происходит инсерт.

Если же от апишки не пришла инфа о студенте, а она есть в БД, то инфа из БД должна удаляться. Это пока не работает, со следующим коммитом исправлю.

Список таблиц, которые в данный момент исправно обновляются:
1. xlogins
2. cursus_users
3. skills
4. projects_users
5. achievements

2019-04-06 08:22 UTC, Millon15 commented on my_info.php
> +$a = array (
Это сгенеренный `var_export()` документ, я этот код не писал. Удалю его из гита со следующим коммитом.

2019-04-08 13:33 UTC, setnemo approved these changes

2019-04-08 13:33 UTC, omentes commented
Тестил, работает? @Millon15

2019-04-08 17:49 UTC, Millon15 commented
@omentes Вот теперь полностью работает. Довольно идеально. Единственное, что я не понял, так это откуда нам брать поля `hours` и `lasthours`

2019-04-20 17:13 UTC, merged